#!/usr/bin/env node
/**
 * Journals — Interactive Setup
 *
 * Run: node setup.js
 * Or:  npm run setup
 *
 * Walks you through configuring your journal instance,
 * generates sample entries, and gets you ready to run.
 */

import { createInterface } from 'readline'
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'
import { execSync } from 'child_process'

const __dirname = dirname(fileURLToPath(import.meta.url))
const CONFIG_PATH = join(__dirname, 'journals.config.js')

const rl = createInterface({ input: process.stdin, output: process.stdout })
const ask = (q, fallback = '') => new Promise(resolve => {
  rl.question(`${q}${fallback ? ` (${fallback})` : ''}: `, answer => {
    resolve(answer.trim() || fallback)
  })
})

async function main() {
  console.log()
  console.log('  Journals — Setup Wizard')
  console.log('  ━━━━━━━━━━━━━━━━━━━━━━')
  console.log()

  // 1. Basic info
  const name = await ask('  Your name', 'User')
  const siteTitle = await ask('  Site title', 'Journals')

  // 2. Weather
  const weatherEnabled = (await ask('  Enable weather widget? (y/n)', 'y')).toLowerCase() === 'y'
  let lat = '40.71', lon = '-74.01', weatherLabel = 'New York'
  if (weatherEnabled) {
    console.log('  Find your coordinates at https://open-meteo.com')
    lat = await ask('  Latitude', '40.71')
    lon = await ask('  Longitude', '-74.01')
    weatherLabel = await ask('  Location name (for your reference)', 'New York')
  }

  // 3. Data sources
  console.log()
  console.log('  Data Sources')
  console.log('  ────────────')
  const reposDir = await ask('  Git repos directory (relative to ~)', 'GitHub')
  const claudeHistory = await ask('  Claude Code history path (relative to ~)', '.claude/history.jsonl')
  const narrativeInput = await ask('  Narrative journal dir (relative to ~, or "skip")', 'skip')
  const narrativeDir = narrativeInput === 'skip' ? null : narrativeInput

  // 4. Git auto-push
  const autoPush = (await ask('  Auto-push after generation? (y/n)', 'n')).toLowerCase() === 'y'
  const branch = autoPush ? await ask('  Push branch', 'main') : 'main'

  // 5. Claude API (for Reflect feature)
  const reflectEnabled = (await ask('  Enable AI Reflect feature? Requires Claude API key (y/n)', 'n')).toLowerCase() === 'y'

  // Write config
  const config = `/**
 * Journals — User Configuration
 * Generated by setup wizard on ${new Date().toISOString().slice(0, 10)}
 */

export default {
  name: '${name}',
  siteTitle: '${siteTitle}',

  weather: {
    enabled: ${weatherEnabled},
    latitude: ${lat},
    longitude: ${lon},
    label: '${weatherLabel}',
  },

  sources: {
    claudeHistory: '${claudeHistory}',
    reposDir: '${reposDir}',
    narrativeDir: ${narrativeDir ? `'${narrativeDir}'` : 'null'},
  },

  git: {
    autoPush: ${autoPush},
    branch: '${branch}',
  },

  reflect: {
    enabled: ${reflectEnabled},
    model: 'claude-haiku-4-5-20251001',
  },
}
`
  writeFileSync(CONFIG_PATH, config)
  console.log()
  console.log('  Config saved to journals.config.js')

  // Create .env if reflect enabled
  if (reflectEnabled) {
    const envPath = join(__dirname, 'app', '.env')
    if (!existsSync(envPath)) {
      const apiKey = await ask('  Your Anthropic API key (sk-ant-...)', '')
      if (apiKey) {
        writeFileSync(envPath, `VITE_ANTHROPIC_API_KEY=${apiKey}\n`)
        console.log('  API key saved to app/.env')
      } else {
        console.log('  Skipped — add your key to app/.env later')
      }
    }
  }

  // Generate sample entries
  console.log()
  const genSample = (await ask('  Generate sample entries to see how it looks? (y/n)', 'y')).toLowerCase() === 'y'
  if (genSample) {
    generateSampleEntries()
    console.log('  Sample entries generated.')
  }

  // Install dependencies
  console.log()
  console.log('  Installing dependencies...')
  try {
    execSync('npm install', { cwd: join(__dirname, 'app'), stdio: 'inherit' })
  } catch {
    console.log('  npm install failed — run it manually: cd app && npm install')
  }

  // Done
  console.log()
  console.log('  Setup complete!')
  console.log()
  console.log('  Next steps:')
  console.log('    cd app && npm run dev        Start dev server')
  console.log('    python3 scripts/generate_all.py   Generate today\'s entries')
  console.log()

  rl.close()
}

function generateSampleEntries() {
  const today = new Date().toISOString().slice(0, 10)
  const yesterday = new Date(Date.now() - 86400000).toISOString().slice(0, 10)
  const dayBefore = new Date(Date.now() - 86400000 * 2).toISOString().slice(0, 10)

  const days = [
    { date: dayBefore, dayName: getDayName(dayBefore) },
    { date: yesterday, dayName: getDayName(yesterday) },
    { date: today, dayName: getDayName(today) },
  ]

  const workDir = join(__dirname, 'app', 'public', 'entries', 'work')
  const dailyDir = join(__dirname, 'app', 'public', 'entries', 'daily')
  const narrativeDir = join(__dirname, 'app', 'public', 'entries', 'narrative')
  mkdirSync(workDir, { recursive: true })
  mkdirSync(dailyDir, { recursive: true })
  mkdirSync(narrativeDir, { recursive: true })

  for (const { date, dayName } of days) {
    const dt = new Date(date + 'T12:00:00')
    const display = dt.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })

    // Work entry
    const sessions = 1 + Math.floor(Math.random() * 4)
    const commits = 2 + Math.floor(Math.random() * 8)
    const messages = sessions * (10 + Math.floor(Math.random() * 20))
    writeFileSync(join(workDir, `${date}.json`), JSON.stringify({
      date, day: dayName, display,
      generatedAt: new Date().toISOString(),
      metrics: {
        volume: { score: 40 + Math.floor(Math.random() * 40), label: 'Output Volume' },
        complexity: { score: 30 + Math.floor(Math.random() * 40), label: 'Complexity' },
        focus: { score: 50 + Math.floor(Math.random() * 30), label: 'Focus' },
        depth: { score: 40 + Math.floor(Math.random() * 40), label: 'Depth' },
        craft: { score: 50 + Math.floor(Math.random() * 30), label: 'Craft' },
        momentum: { score: 30 + Math.floor(Math.random() * 50), label: 'Momentum' },
      },
      stats: { sessions, messages, commits, repos: 1, timeRange: '09:00–17:30', linesAdded: commits * 45, linesRemoved: commits * 12, filesChanged: commits * 3 },
      whatIDid: ['Set up Journals project and configured local environment', 'Explored the codebase and customized themes'],
      activityTimeline: ['Project setup and configuration', 'Theme customization'],
      insights: ['Getting familiar with the workflow — momentum will build as the habit forms.'],
      continuedFromYesterday: [],
      roadblocks: [],
      themes: { 'General Development': 3, 'Page Building': 2 },
      projectsWip: ['journals — sample data'],
      gitActivity: [{ repo: 'journals', commits: [{ hash: 'abc1234', author: 'You', message: 'Initial setup', time: '10:00' }], stat: `${commits * 3} files changed, ${commits * 45} insertions(+)` }],
      summary: `${sessions} session(s), ${messages} msgs, ${commits} commit(s) across 1 repo(s)`,
    }, null, 2))

    // Daily entry
    const commands = 20 + Math.floor(Math.random() * 60)
    writeFileSync(join(dailyDir, `${date}.json`), JSON.stringify({
      date, day: dayName, display,
      generatedAt: new Date().toISOString(),
      summary: `${commands} terminal commands, ${commits} commits across 1 repos, 0 files modified.`,
      stats: { commands, commits, repos: 1, filesModified: 0 },
      categories: { Git: Math.floor(commands * 0.3), Navigation: Math.floor(commands * 0.2), 'Claude Code': Math.floor(commands * 0.15), Other: Math.floor(commands * 0.35) },
      activityByHour: { '09': 5, '10': 8, '11': 12, '14': 10, '15': 7, '16': 5 },
      notableCommands: [{ time: '10:00', command: 'npm run dev' }, { time: '14:30', command: 'git log --oneline -10' }],
      gitActivity: [],
      fileGroups: {},
    }, null, 2))
  }

  // Build manifest
  const manifest = { work: [], daily: [], narrative: [] }
  for (const { date, dayName } of days) {
    const dt = new Date(date + 'T12:00:00')
    const display = dt.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })
    const workData = JSON.parse(readFileSync(join(workDir, `${date}.json`), 'utf-8'))
    const dailyData = JSON.parse(readFileSync(join(dailyDir, `${date}.json`), 'utf-8'))
    manifest.work.push({ date, day: dayName, display, summary: workData.summary, stats: workData.stats })
    manifest.daily.push({ date, day: dayName, display, summary: dailyData.summary, stats: dailyData.stats })
  }
  writeFileSync(join(__dirname, 'app', 'public', 'manifest.json'), JSON.stringify(manifest, null, 2))
}

function getDayName(dateStr) {
  return new Date(dateStr + 'T12:00:00').toLocaleDateString('en-US', { weekday: 'long' })
}

main().catch(console.error)
